server:
  port: 8095

spring:
  datasource:
    url: jdbc:mysql://172.25.0.2:3306/sakila
    username: user
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

application:
  title: Puzzled Pig Movies
  version: v1.1.0

