server:
  port: 8095

spring:
  datasource:
    url: jdbc:mysql://172.17.0.2/sakila
    username: user
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

application:
  title: Puzzled Pig Movies
  version: v1.1.0

